### ISSUE TITLE
404

### ISSUE THREAD

**Issue by AeyKeyZS** [qsniyg/rssit#8]
Getting 404 when opening http://localhost:8123/ in browser

__________________________________________________________________________________________________________
In my Windows 10 Command prompt:
----------------------------------------------

No module named 'dbus'
Warning: one of dbus-python or gobject is missing, so no notification supportNo module named 'dbus'
Trying port 8123
Warning: one of dbus-python or gobject is missing, so no notification support

__________________________________________________________________________________________________________

When I am trying to install dbus:
----------------------------------------

Collecting dbus-python
  Using cached https://files.pythonhosted.org/packages/62/7e/d4fb56a1695fa65da0c8d3071855fa5408447b913c58c01933c2f81a269a/dbus-python-1.2.16.tar.gz
Installing collected packages: dbus-python
  Running setup.py install for dbus-python ... error
    Complete output from command e:\py\env\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\aksha\\AppData\\Local\\Temp\\pip-install-qqm7gf83\\dbus-python\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\aksha\AppData\Local\Temp\pip-record-agf95m5f\install-record.txt --single-version-externally-managed --compile --install-headers e:\py\env\include\site\python3.7\dbus-python:
    running install
    running build
    creating C:\Users\aksha\AppData\Local\Temp\pip-install-qqm7gf83\dbus-python\build
    creating C:\Users\aksha\AppData\Local\Temp\pip-install-qqm7gf83\dbus-python\build\temp.win32-3.7
    **error: [WinError 193] %1 is not a valid Win32 application**

**Comment by qsniyg** [comment]
I haven't tested it under windows 10 (other than through cygwin/WSL, both of which do work), so it's probably something relating to that.

Dbus is only needed for system notifications support under linux, and rssit can run fine without it, so the 404 issue isn't that.

I'm not quite sure what would cause the issue though. Looking at the source code, I don't see anything that looks too linux-specific... does rssit end after the last message, or does it stay running?

Also, does it return a 404 error, or does it return something more along the lines of "This site can’t be reached"?

**Comment by AeyKeyZS** [comment]
No... rssit is not saying anything else... it ending up there only...
When I hit the port it only adds:
___________________________________________________________________________________________________________No module named 'dbus'
Warning: one of dbus-python or gobject is missing, so no notification supportNo module named 'dbus'
Trying port 8123
Warning: one of dbus-python or gobject is missing, so no notification support127.0.0.1 - - [02/Feb/2020 12:34:24] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [02/Feb/2020 12:39:48] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [02/Feb/2020 12:42:17] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [02/Feb/2020 12:45:40] "GET / HTTP/1.1" 404 -
___________________________________________________________________________________________________________
which is a response only...

It's ending up here. No other messages

**Comment by AeyKeyZS** [comment]
Giving a try with cygwin

**Comment by qsniyg** [comment]
Wow, that's really strange... Could you see if http://localhost:8123/f works?

**Comment by AeyKeyZS** [comment]
> Wow, that's really strange... Could you see if http://localhost:8123/f works?

No! It's not

**Comment by AeyKeyZS** [comment]
Any configurations that I need to do before running the application?
With cygwin, I am facing the same issue:
___________________________________________________________________________________________________________
```
No module named 'dbus'
Warning: one of dbus-python or gobject is missing, so no notification supportNo
module named 'dbus'
Trying port 8123
Warning: one of dbus-python or gobject is missing, so no notification support127
.0.0.1 - - [02/Feb/2020 09:02:05] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [02/Feb/2020 09:02:09] "GET /f HTTP/1.1" 404 -
```
___________________________________________________________________________________________________________
Help!!!

**Comment by qsniyg** [comment]
Alright, that is really strange... Could you edit rssit/path.py, and add this line?

```
def process(server, path):
    print(rssit.paths.all.paths_dict, path) # <- Add this line
    normpath = re.sub("^/*", "", os.path.normpath(path))
```

Then restart rssit and share the output?

**Comment by AeyKeyZS** [comment]
> Alright, that is really strange... Could you edit rssit/path.py, and add this line?
> 
> ```
> def process(server, path):
>     print(rssit.paths.all.paths_dict, path) # <- Add this line
>     normpath = re.sub("^/*", "", os.path.normpath(path))
> ```
> 
> Then restart rssit and share the output?

Here is the output:
```
No module named 'dbus'
Warning: one of dbus-python or gobject is missing, so no notification supportNo module named 'dbus'
Trying port 8123
Warning: one of dbus-python or gobject is missing, so no notification support{'': {'path': '', 'process': <function process at 0x02F9A1E0>}, 'reload': {'path': 'reload', 'process': <function process at 0x038B3C
00>}, 'update': {'path': 'update', 'process': <function process at 0x038B3DB0>}, 'f': {'path': 'f', 'init': <function init at 0x038B3D68>, 'process': <function process at 0x038EDD20>}, 'player': {'path': 'playe
r', 'process': <function process at 0x038B3B28>}, 'status': {'path': 'status', 'process': <function process at 0x0384FB70>}, '404': {'path': '404', 'process': <function process at 0x0384FBB8>}, 'resetcookiejar'
: {'path': 'resetcookiejar', 'process': <function process at 0x0384FC00>}} /f
127.0.0.1 - - [02/Feb/2020 09:21:29] "GET /f HTTP/1.1" 404 -

```

**Comment by qsniyg** [comment]
Now I'm really confused haha. Could you modify it to this?

```
def process(server, path):
    normpath = re.sub("^/*", "", os.path.normpath(path))
    newpath, options = questionmark(normpath)
    path_name = re.sub("@.*", "", newpath.split("/")[0].lower())
    print(path_name) # <- Add this line

    path_list = rssit.paths.all.paths_dict

    if path_name not in path_list:
        print("not in path_list") # <- Add this line
        path_name = "404"
```

Also, after trying through http://localhost:8123/f, could you then run rssit as:

`python3 rssit.py '/f' nohooks=true output=social`

And share that output too?

**Comment by AeyKeyZS** [comment]
After adding your snippet:
```
No module named 'dbus'
Warning: one of dbus-python or gobject is missing, so no notification supportNo module named 'dbus'
Trying port 8123
Warning: one of dbus-python or gobject is missing, so no notification support\
not in path_list
127.0.0.1 - - [02/Feb/2020 09:44:19] "GET / HTTP/1.1" 404 -
\f
not in path_list
127.0.0.1 - - [02/Feb/2020 09:44:25] "GET /f HTTP/1.1" 404 -
```

And after python3 rssit.py '/f' nohooks=true output=social
```
(env) E:\PY\rssit-master\rssit-master>python rssit.py '/f' nohooks=true output=social
No module named 'dbus'
Warning: one of dbus-python or gobject is missing, so no notification supportNo module named 'dbus'
Trying port 8123
Warning: one of dbus-python or gobject is missing, so no notification support\
not in path_list
127.0.0.1 - - [02/Feb/2020 15:16:53] "GET / HTTP/1.1" 404 -
\f
not in path_list
127.0.0.1 - - [02/Feb/2020 15:16:56] "GET /f HTTP/1.1" 404
```

It must be annoying

**Comment by qsniyg** [comment]
Awesome! Found the problem, it was because I was calling `os.path.normpath`, without realizing that this replaced forward slashes to backslashes on windows.

Either undo the changes or `git reset --hard HEAD` then `git pull` :)
